# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/diffusion_curvature',
                'doc_host': 'https://professorwug.github.io',
                'git_url': 'https://github.com/professorwug/diffusion_curvature',
                'lib_path': 'diffusion_curvature'},
  'syms': {'diffusion_curvature.core': {'diffusion_curvature.core.foo': ('core.html#foo', 'diffusion_curvature/core.py')}}}
