# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/diffusion_curvature',
                'doc_host': 'https://professorwug.github.io',
                'git_url': 'https://github.com/professorwug/diffusion_curvature',
                'lib_path': 'diffusion_curvature'},
  'syms': { 'diffusion_curvature.core': {'diffusion_curvature.core.foo': ('core.html#foo', 'diffusion_curvature/core.py')},
            'diffusion_curvature.datasets': { 'diffusion_curvature.datasets.ellipsoid': ( 'datasets.html#ellipsoid',
                                                                                          'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.hyperboloid': ( 'datasets.html#hyperboloid',
                                                                                            'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.paraboloid': ( 'datasets.html#paraboloid',
                                                                                           'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.plane': ( 'datasets.html#plane',
                                                                                      'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.rejection_sample_for_ellipsoid': ( 'datasets.html#rejection_sample_for_ellipsoid',
                                                                                                               'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.rejection_sample_for_hyperboloid': ( 'datasets.html#rejection_sample_for_hyperboloid',
                                                                                                                 'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.rejection_sample_for_saddle': ( 'datasets.html#rejection_sample_for_saddle',
                                                                                                            'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.rejection_sample_for_torus': ( 'datasets.html#rejection_sample_for_torus',
                                                                                                           'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.sphere': ( 'datasets.html#sphere',
                                                                                       'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.torus': ( 'datasets.html#torus',
                                                                                      'diffusion_curvature/datasets.py')},
            'diffusion_curvature.distances': { 'diffusion_curvature.distances.phate_distances': ( 'manifold distances.html#phate_distances',
                                                                                                  'diffusion_curvature/distances.py')},
            'diffusion_curvature.graphs': { 'diffusion_curvature.graphs.diff_aff': ( 'graphs.html#diff_aff',
                                                                                     'diffusion_curvature/graphs.py'),
                                            'diffusion_curvature.graphs.diff_op': ('graphs.html#diff_op', 'diffusion_curvature/graphs.py'),
                                            'diffusion_curvature.graphs.get_alpha_decay_graph': ( 'graphs.html#get_alpha_decay_graph',
                                                                                                  'diffusion_curvature/graphs.py'),
                                            'diffusion_curvature.graphs.get_knn_graph': ( 'graphs.html#get_knn_graph',
                                                                                          'diffusion_curvature/graphs.py'),
                                            'diffusion_curvature.graphs.get_scanpy_graph': ( 'graphs.html#get_scanpy_graph',
                                                                                             'diffusion_curvature/graphs.py'),
                                            'diffusion_curvature.graphs.get_umap_graph': ( 'graphs.html#get_umap_graph',
                                                                                           'diffusion_curvature/graphs.py'),
                                            'diffusion_curvature.graphs.kernel_degree': ( 'graphs.html#kernel_degree',
                                                                                          'diffusion_curvature/graphs.py')},
            'diffusion_curvature.graphtools': { 'diffusion_curvature.graphtools.DiffusionCurvature': ( 'core '
                                                                                                       '(graphtools).html#diffusioncurvature',
                                                                                                       'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.__init__': ( 'core '
                                                                                                                '(graphtools).html#diffusioncurvature.__init__',
                                                                                                                'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.curvature': ( 'core '
                                                                                                                 '(graphtools).html#diffusioncurvature.curvature',
                                                                                                                 'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.distances': ( 'core '
                                                                                                                 '(graphtools).html#diffusioncurvature.distances',
                                                                                                                 'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.entropy_of_diffusion': ( 'core '
                                                                                                                            '(graphtools).html#diffusioncurvature.entropy_of_diffusion',
                                                                                                                            'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.flattened_facsimile_of_graph': ( 'core '
                                                                                                                                    '(graphtools).html#diffusioncurvature.flattened_facsimile_of_graph',
                                                                                                                                    'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.power_diffusion_matrix': ( 'core '
                                                                                                                              '(graphtools).html#diffusioncurvature.power_diffusion_matrix',
                                                                                                                              'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.wasserstein_spread_of_diffusion': ( 'core '
                                                                                                                                       '(graphtools).html#diffusioncurvature.wasserstein_spread_of_diffusion',
                                                                                                                                       'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.get_graph_type': ( 'core (graphtools).html#get_graph_type',
                                                                                                   'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.plot_manifold_curvature': ( 'core '
                                                                                                            '(graphtools).html#plot_manifold_curvature',
                                                                                                            'diffusion_curvature/graphtools.py')},
            'diffusion_curvature.heatkernel': { 'diffusion_curvature.heatkernel.E': ( 'neumann heat kernel via chebyshev '
                                                                                      'approximation.html#e',
                                                                                      'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.compute_chebychev_coeff_all': ( 'neumann heat kernel via '
                                                                                                                'chebyshev '
                                                                                                                'approximation.html#compute_chebychev_coeff_all',
                                                                                                                'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.expm_multiply': ( 'neumann heat kernel via chebyshev '
                                                                                                  'approximation.html#expm_multiply',
                                                                                                  'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.g': ( 'neumann heat kernel via chebyshev '
                                                                                      'approximation.html#g',
                                                                                      'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.get_bound_bergamaschi_generic': ( 'neumann heat kernel via '
                                                                                                                  'chebyshev '
                                                                                                                  'approximation.html#get_bound_bergamaschi_generic',
                                                                                                                  'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.get_bound_bergamaschi_specific': ( 'neumann heat kernel '
                                                                                                                   'via chebyshev '
                                                                                                                   'approximation.html#get_bound_bergamaschi_specific',
                                                                                                                   'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.get_bound_eps_generic': ( 'neumann heat kernel via '
                                                                                                          'chebyshev '
                                                                                                          'approximation.html#get_bound_eps_generic',
                                                                                                          'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.get_bound_eta_generic': ( 'neumann heat kernel via '
                                                                                                          'chebyshev '
                                                                                                          'approximation.html#get_bound_eta_generic',
                                                                                                          'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.get_bound_eta_specific': ( 'neumann heat kernel via '
                                                                                                           'chebyshev '
                                                                                                           'approximation.html#get_bound_eta_specific',
                                                                                                           'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.heat_diffusion_on_signal': ( 'neumann heat kernel via '
                                                                                                             'chebyshev '
                                                                                                             'approximation.html#heat_diffusion_on_signal',
                                                                                                             'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.kronecker_delta': ( 'neumann heat kernel via chebyshev '
                                                                                                    'approximation.html#kronecker_delta',
                                                                                                    'diffusion_curvature/heatkernel.py'),
                                                'diffusion_curvature.heatkernel.reverse_bound': ( 'neumann heat kernel via chebyshev '
                                                                                                  'approximation.html#reverse_bound',
                                                                                                  'diffusion_curvature/heatkernel.py')},
            'diffusion_curvature.kernels': { 'diffusion_curvature.kernels.compute_anisotropic_affinities_from_graph': ( 'kernels.html#compute_anisotropic_affinities_from_graph',
                                                                                                                        'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.compute_anisotropic_diffusion_matrix_from_graph': ( 'kernels.html#compute_anisotropic_diffusion_matrix_from_graph',
                                                                                                                              'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.diffusion_matrix': ( 'kernels.html#diffusion_matrix',
                                                                                               'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.gaussian_kernel': ( 'kernels.html#gaussian_kernel',
                                                                                              'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.median_heuristic': ( 'kernels.html#median_heuristic',
                                                                                               'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.plot_3d': ( 'kernels.html#plot_3d',
                                                                                      'diffusion_curvature/kernels.py')},
            'diffusion_curvature.laziness': { 'diffusion_curvature.laziness.entropy_of_diffusion': ( 'diffusion '
                                                                                                     'laziness.html#entropy_of_diffusion',
                                                                                                     'diffusion_curvature/laziness.py')},
            'diffusion_curvature.manifold_graph': { 'diffusion_curvature.manifold_graph.ManifoldGraph': ( 'core '
                                                                                                          '(manifoldgraph).html#manifoldgraph',
                                                                                                          'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.ManifoldGraph.__init__': ( 'core '
                                                                                                                   '(manifoldgraph).html#manifoldgraph.__init__',
                                                                                                                   'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.ManifoldGraph.num_nodes': ( 'core '
                                                                                                                    '(manifoldgraph).html#manifoldgraph.num_nodes',
                                                                                                                    'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.diffusion_curvature': ( 'core '
                                                                                                                '(manifoldgraph).html#diffusion_curvature',
                                                                                                                'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.diffusion_entropy_curvature': ( 'core '
                                                                                                                        '(manifoldgraph).html#diffusion_entropy_curvature',
                                                                                                                        'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.entropy_of_diffusion': ( 'core '
                                                                                                                 '(manifoldgraph).html#entropy_of_diffusion',
                                                                                                                 'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.flattened_facsimile_of_graph': ( 'core '
                                                                                                                         '(manifoldgraph).html#flattened_facsimile_of_graph',
                                                                                                                         'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.phate_distances': ( 'core '
                                                                                                            '(manifoldgraph).html#phate_distances',
                                                                                                            'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.plot_manifold_curvature': ( 'core '
                                                                                                                    '(manifoldgraph).html#plot_manifold_curvature',
                                                                                                                    'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.power_diffusion_matrix': ( 'core '
                                                                                                                   '(manifoldgraph).html#power_diffusion_matrix',
                                                                                                                   'diffusion_curvature/manifold_graph.py'),
                                                    'diffusion_curvature.manifold_graph.wasserstein_spread_of_diffusion': ( 'core '
                                                                                                                            '(manifoldgraph).html#wasserstein_spread_of_diffusion',
                                                                                                                            'diffusion_curvature/manifold_graph.py')},
            'diffusion_curvature.utils': { 'diffusion_curvature.utils.kronecker_delta': ( 'utils.html#kronecker_delta',
                                                                                          'diffusion_curvature/utils.py'),
                                           'diffusion_curvature.utils.perform_trials': ( 'utils.html#perform_trials',
                                                                                         'diffusion_curvature/utils.py'),
                                           'diffusion_curvature.utils.plot_3d': ('utils.html#plot_3d', 'diffusion_curvature/utils.py'),
                                           'diffusion_curvature.utils.plot_array': ( 'utils.html#plot_array',
                                                                                     'diffusion_curvature/utils.py')},
            'diffusion_curvature.volume': { 'diffusion_curvature.volume.actual_euclidean_volumes_at_radii': ( 'volume '
                                                                                                              'estimation.html#actual_euclidean_volumes_at_radii',
                                                                                                              'diffusion_curvature/volume.py'),
                                            'diffusion_curvature.volume.calculate_radius_offset': ( 'volume '
                                                                                                    'estimation.html#calculate_radius_offset',
                                                                                                    'diffusion_curvature/volume.py'),
                                            'diffusion_curvature.volume.volume_via_heat_at_scales': ( 'volume '
                                                                                                      'estimation.html#volume_via_heat_at_scales',
                                                                                                      'diffusion_curvature/volume.py')},
            'diffusion_curvature.volume_comparison': { 'diffusion_curvature.volume_comparison.extract_scalar_curvature': ( 'curvature by '
                                                                                                                           'quadratic '
                                                                                                                           'fitting.html#extract_scalar_curvature',
                                                                                                                           'diffusion_curvature/volume_comparison.py'),
                                                       'diffusion_curvature.volume_comparison.extract_scalar_curvature_with_offset_compensation': ( 'curvature '
                                                                                                                                                    'by '
                                                                                                                                                    'quadratic '
                                                                                                                                                    'fitting.html#extract_scalar_curvature_with_offset_compensation',
                                                                                                                                                    'diffusion_curvature/volume_comparison.py'),
                                                       'diffusion_curvature.volume_comparison.scalar_curvatures_of_graph': ( 'curvature by '
                                                                                                                             'quadratic '
                                                                                                                             'fitting.html#scalar_curvatures_of_graph',
                                                                                                                             'diffusion_curvature/volume_comparison.py'),
                                                       'diffusion_curvature.volume_comparison.volume_comparisons_of_graph_at_idx': ( 'curvature '
                                                                                                                                     'by '
                                                                                                                                     'quadratic '
                                                                                                                                     'fitting.html#volume_comparisons_of_graph_at_idx',
                                                                                                                                     'diffusion_curvature/volume_comparison.py')}}}
