# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/3a2 Hickok Curvature of Battery.ipynb.

# %% auto 0
__all__ = ['result_table']

# %% ../nbs/3a2 Hickok Curvature of Battery.ipynb 10
# Make a latex table of the correlations, both r and p values, with dimension in the rows and noise level in the columns
from tabulate import tabulate
def result_table(
        correlations, # dictionary of correlations
        c:int, # codimension
        style = 'fancy_grid'
        ):
    noise_levels = correlations[correlations.keys().__iter__().__next__()][c].keys()
    print("Codimension = ",c)
    table = tabulate(
        [[d] + [f"{correlations[d][c][noise_level]['r']:.{3}f}/{correlations[d][c][noise_level]['p']:.{3}f}" for noise_level in noise_levels] for d in correlations.keys()],
        headers=['dim'] + [f"Noise = {nl}" for nl in noise_levels],
        tablefmt=style, #latex_raw
        floatfmt=".2f",
        )
    print(table)
    return table
