# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Diffusion Laziness.ipynb.

# %% auto 0
__all__ = ['entropy_of_diffusion']

# %% ../nbs/Diffusion Laziness.ipynb 3
def entropy_of_diffusion(G:graphtools.graphs.DataGraph, idx=None):
        """
        Returns the pointwise entropy of diffusion from the powered diffusion matrix in the inpiut 
        """
        assert G.Pt is not None
        # TODO: Entropy may be compatible with scipy.sparse matrices
        if type(G.Pt) == np.ndarray:
            Pt = G.Pt
        else:
            Pt = G.Pt.toarray()
        if idx is None:
            return entropy(Pt, axis=1)
        else:
            return entropy(Pt[idx])
